<?php $pager = $this->renderPager($p, null, $params, $get); ?>

<?php echo $pager; ?>
<table class="table table-striped table-bordered table-hover table-full-width crud-<?php echo $table; ?>">
    <thead>
        <tr>
            <?php foreach ($cols as $col): ?>
                <?php if (isset($hide[$col])): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <th>
                    <?php echo label($col); ?>
                </th>

            <?php endforeach; ?>
            <th><i class="fa fa-cogs"></i></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($list as $item): ?>
            <tr>
                <?php foreach ($cols as $col): ?>
                    <?php if (isset($hide[$col])): ?>
                        <?php continue; ?>
                    <?php endif; ?>
                    <td>
                        <?php echo $item[$col]; ?>
                    </td>
                <?php endforeach; ?>
                <td>
                    <div class="btn-group">
                        <?php echo $definition->options($item, $list, $options); ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $pager; ?>
