<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Chave</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th><i class="fa fa-cogs"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->config as $key => $value): ?>
            <tr>
                <td><?php echo $key; ?></td>
                <td><?php echo $this->config->descriptionMap[$key]; ?></td>
                <td><pre><small><?php echo nl2br($value); ?></small></pre></td>
                <td>
                    <a href="<?php echo $this->link('admin/config/update', array('chave' => $key)); ?>" class="btn btn-large btn-primary"><i class="fa fa-pencil"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
